# Flask 추론 서버 설정

# 서버 설정
server:
  host: 0.0.0.0  # 모든 인터페이스에서 접근 허용
  port: 5000  # 서버 포트
  debug: false  # 프로덕션에서는 false
  threaded: true  # 멀티스레딩 활성화

# AI 모델 설정
model:
  device: cuda  # cuda 또는 cpu
  yolo_model_path: models/yolo/final/yolo_best.pt  # YOLO 모델 경로
  anomaly_model_path: models/anomaly/padim/model.pth  # 이상 탐지 모델 (Phase 4)
  confidence_threshold: 0.25  # 최소 confidence
  iou_threshold: 0.7  # NMS IoU threshold
  use_fp16: true  # FP16 사용 (RTX 4080 Super 최적화)

# 추론 설정
inference:
  max_batch_size: 2  # 동시 처리 최대 배치 크기 (좌측+우측)
  timeout: 5.0  # 추론 타임아웃 (초)
  enable_anomaly_detection: false  # 이상 탐지 활성화 (Phase 4)

# 데이터베이스 설정 (MySQL)
database:
  host: localhost  # Tailscale: 100.x.x.x
  port: 3306
  user: pcb_user  # 데이터베이스 사용자
  password: your_password_here  # 비밀번호 (환경 변수 사용 권장)
  database: pcb_inspection  # 데이터베이스 이름
  charset: utf8mb4

# 로깅 설정
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: logs/server_logs/server.log
  max_bytes: 10485760  # 10MB
  backup_count: 5  # 로그 파일 백업 개수

# CORS 설정
cors:
  enabled: true
  origins: ["*"]  # 허용할 origin (프로덕션에서는 제한 필요)

# 이미지 저장 설정
storage:
  save_defect_images: true  # 불량 이미지 저장 여부
  defect_images_path: data/defect_images  # 불량 이미지 저장 경로
  max_image_size: 1920  # 최대 이미지 크기 (픽셀)

# 성능 모니터링
monitoring:
  enable_metrics: true  # 성능 지표 수집
  metrics_interval: 60  # 지표 수집 간격 (초)
